import { VocabularyWord } from "./types/database.types";

// Sample vocabulary for demo quiz - Attack on Titan themed
export const demoVocabulary: VocabularyWord[] = [
  {
    id: "demo-1",
    vocabulary_list_id: "demo",
    word: "進撃",
    reading: "しんげき",
    meaning: "advance/attack",
    order_index: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    vocabulary_list_id: "demo",
    word: "巨人",
    reading: "きょじん",
    meaning: "giant/titan",
    order_index: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    vocabulary_list_id: "demo",
    word: "壁",
    reading: "かべ",
    meaning: "wall",
    order_index: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    vocabulary_list_id: "demo",
    word: "調査",
    reading: "ちょうさ",
    meaning: "investigation/survey",
    order_index: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-5",
    vocabulary_list_id: "demo",
    word: "兵団",
    reading: "へいだん",
    meaning: "corps/regiment",
    order_index: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-6",
    vocabulary_list_id: "demo",
    word: "人類",
    reading: "じんるい",
    meaning: "humanity/mankind",
    order_index: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-7",
    vocabulary_list_id: "demo",
    word: "戦闘",
    reading: "せんとう",
    meaning: "battle/combat",
    order_index: 7,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-8",
    vocabulary_list_id: "demo",
    word: "訓練",
    reading: "くんれん",
    meaning: "training",
    order_index: 8,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-9",
    vocabulary_list_id: "demo",
    word: "自由",
    reading: "じゆう",
    meaning: "freedom",
    order_index: 9,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-10",
    vocabulary_list_id: "demo",
    word: "世界",
    reading: "せかい",
    meaning: "world",
    order_index: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-11",
    vocabulary_list_id: "demo",
    word: "敵",
    reading: "てき",
    meaning: "enemy",
    order_index: 11,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-12",
    vocabulary_list_id: "demo",
    word: "仲間",
    reading: "なかま",
    meaning: "companion/comrade",
    order_index: 12,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-13",
    vocabulary_list_id: "demo",
    word: "危険",
    reading: "きけん",
    meaning: "danger",
    order_index: 13,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-14",
    vocabulary_list_id: "demo",
    word: "希望",
    reading: "きぼう",
    meaning: "hope",
    order_index: 14,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-15",
    vocabulary_list_id: "demo",
    word: "未来",
    reading: "みらい",
    meaning: "future",
    order_index: 15,
    created_at: new Date().toISOString(),
  },
];

